pipeline {
    agent any

    stages {
        stage('Clone Repository') {
            steps {
                git 'https://github.com/SRCEM-AIM-Class-A/A37_DhruvKrishnani_DjangoApp.git'
            }
        }
        stage('Build Docker Image') {
            steps {
                sh 'docker build -t dhruvkrishnani2/studentproject .'
            }
        }
        stage('Push to Docker Hub') {
            steps {
                withDockerRegistry([credentialsId: 'docker-hub-credentials', url: '']) {
                    sh 'docker push dhruvkrishnani2/studentproject'
                }
            }
        }
    }
}
